version: '2'
services:
  server:
    image: to-go-server
    ports:
      - "8080:8080"
    environment:
      MONGO_URL: mongo:27017
    links:
      - mongo:mongo

  mongo:
    image: mongo:3.6
    ports:
      - "27017:27017"
      - "28017:28017"